# Generated by Django 4.2.17 on 2025-02-07 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='İsim')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug -Lütfen Burayı Değiştirmeyin-')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='İsim')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug -Lütfen Burayı Değiştirmeyin-')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tutar')),
                ('image', models.ImageField(blank=True, upload_to='product', verbose_name='Resim')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok')),
                ('avaible', models.BooleanField(default=True, verbose_name='Yayınlandı')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('name',),
            },
        ),
    ]
