# Generated by Django 4.2.17 on 2025-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Üst Kategori İsmi')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug - Lütfen Burayı Değiştirmeyin-')),
            ],
            options={
                'verbose_name': 'Üst Kategori',
                'verbose_name_plural': 'Üst Kategoriler',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug - Lütfen Burayı Değiştirmeyin-'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug - Lütfen Burayı Değiştirmeyin-'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_categories',
            field=models.ManyToManyField(related_name='categories', to='product.parentcategory', verbose_name='Üst Kategoriler'),
        ),
    ]
