# Generated by Django 4.2.17 on 2025-02-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_parentcategory_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.parentcategory', verbose_name='Üst Kategoriler'),
        ),
    ]
