# Generated by Django 4.2.17 on 2025-02-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, verbose_name='Slug - Lütfen Burayı Değiştirmeyin-'),
        ),
    ]
