# Generated by Django 4.2.17 on 2025-02-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='İsim')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug - Lütfen Burayı Değiştirmeyin-')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='collection', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Koleksiyon',
                'verbose_name_plural': 'Koleksiyonlar',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='product.collection', verbose_name='Koleksiyon'),
        ),
    ]
