# Generated by Django 4.2.17 on 2025-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_collection_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='collection', verbose_name='Resim'),
        ),
    ]
