# Generated by Django 4.2.17 on 2025-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='collection', verbose_name='Resim'),
        ),
    ]
