# Generated by Django 4.2.17 on 2025-02-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_parentcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='imageOne',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='Resim 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageThree',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Resim 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageTwo',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Resim 2'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large')], max_length=2, verbose_name='Beden')),
                ('stock', models.PositiveIntegerField(verbose_name='Stok')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
