# Generated by Django 4.2.17 on 2025-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
            },
        ),
    ]
