# Generated by Django 4.2.17 on 2025-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefon', 'verbose_name_plural': 'Telefon'},
        ),
    ]
