# Generated by Django 4.2.17 on 2025-02-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TL Sipariş Toplamı')),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='E-mail')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('billingName', models.CharField(blank=True, max_length=250, verbose_name='Alıcı Adı')),
                ('billingAddress1', models.CharField(blank=True, max_length=250, verbose_name='Alıcı Adresi')),
                ('billingCity', models.CharField(blank=True, max_length=250, verbose_name='Alıcının Şehri')),
                ('billingPostCode', models.CharField(blank=True, max_length=10, verbose_name='Alıcı Posta Kodu')),
                ('billingCountry', models.CharField(blank=True, max_length=200, verbose_name='Alıcı Ülkesi')),
                ('shippingName', models.CharField(blank=True, max_length=250, verbose_name='Alıcı Adı')),
                ('shippingAddress1', models.CharField(blank=True, max_length=250, verbose_name='Kargo Adresi')),
                ('shippingCity', models.CharField(blank=True, max_length=250, verbose_name='Kargo Şehri')),
                ('shippingPostCode', models.CharField(blank=True, max_length=10, verbose_name='Kargo Posta Kodu')),
                ('shippingCountry', models.CharField(blank=True, max_length=200, verbose_name='Kargo Ülkesi')),
                ('status', models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('Kargoda', 'Kargoda'), ('Teslim Edildi', 'Teslim Edildi')], default='Hazırlanıyor', max_length=15, verbose_name='Durum')),
                ('kargo', models.IntegerField(default=0, verbose_name='Kargo Takip Numarası')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'db_table': 'order',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=250, verbose_name='Ürün')),
                ('quantity', models.IntegerField(verbose_name='Adet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TL Tutar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
