# Generated by Django 4.2.17 on 2025-03-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCountry',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Alıcı Adresi')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Alıcının Şehri')),
                ('postCode', models.CharField(blank=True, max_length=10, verbose_name='Alıcı Posta Kodu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
