# Generated by Django 4.2.17 on 2025-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_billingcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='district',
            field=models.CharField(blank=True, max_length=250, verbose_name='Alıcının İlçesi'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=250, verbose_name='Kargo İlçesi'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='Alıcının İli'),
        ),
    ]
