# Generated by Django 5.0.13 on 2025-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_adress_district_order_district_alter_adress_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='tr', max_length=10)),
                ('conversationId', models.CharField(blank=True, max_length=10)),
                ('token', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failure', 'Başarısız'), ('pending', 'Beklemede')], default='pending', max_length=10)),
            ],
        ),
    ]
