# Generated by Django 5.0.13 on 2025-03-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_paymentmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='user',
        ),
    ]
