# Generated by Django 4.2.17 on 2025-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_paymentmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='district',
            new_name='shippingDistrict',
        ),
        migrations.AddField(
            model_name='order',
            name='billingDistrict',
            field=models.CharField(blank=True, max_length=250, verbose_name='Alıcının İlçesi'),
        ),
    ]
