# Generated by Django 4.2.17 on 2025-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderitem_product_variant_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Sipariş Takip Numarası'),
        ),
    ]
