# Generated by Django 4.2.17 on 2025-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('Kargoda', 'Kargoda'), ('Teslim Edildi', 'Teslim Edildi'), ('Iptal Edildi', 'İptal Edildi')], default='Hazırlanıyor', max_length=15, verbose_name='Durum'),
        ),
    ]
